apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp 
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nest-prisma:v8
        imagePullPolicy: Never
        resources:
          limits:
            memory: "256Mi"
            cpu: "175m"
        ports:
        - containerPort: 3000
        env:
          - name: PORT
            value: '3000'
          - name: DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: postgresql-config
                key: postgresql-host
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: postgresql-user
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: postgresql-password
          - name: DATABASE_NAME
            valueFrom:
              secretKeyRef:
                name: postgresql-secret
                key: postgresql-db
          - name: DATABASE_PORT
            value: '5432'
          - name: DATABASE_SCHEMA
            value: public
          - name: DATABASE_URL
            value: "postgresql://$(DATABASE_USER):$(DATABASE_PASSWORD)@$(DATABASE_HOST):$(DATABASE_PORT)/$(DATABASE_NAME)?schema=$(DATABASE_SCHEMA)"
          - name: ELASTICSEARCH_HOST
            valueFrom:
              configMapKeyRef:
                name: elasticsearch-config
                key: elasticsearch-host
          - name: ELASTICSEARCH_NODE
            value: "http://$(ELASTICSEARCH_HOST):9200"
