steps:

- name: 'gcr.io/cloud-builders/npm'
  id: 'install'
  args:
  - 'install'

- name: 'gcr.io/cloud-builders/npm'
  id: 'unit-tests'
  entrypoint: 'npm'
  args:
  - 'run'
  - 'test'

# - name: 'gcr.io/cloud-builders/npm'
#   id: 'e2e-tests'
#   entrypoint: 'npm'
#   args:
#   - 'run'
#   - 'test:e2e'

- name: 'gcr.io/cloud-builders/npm'
  id: 'lint'
  entrypoint: 'npm'
  args:
  - 'run'
  - 'lint'

- name: 'gcr.io/cloud-builders/docker'
  id: 'build'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA'
  - '-t'
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA
  - '--file'
  - 'Dockerfile'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  id: 'push'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA'

- name: 'gcr.io/cloud-builders/docker'
  id: 'push to artifact registry'
  args:
  - 'push'
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_IMAGE_NAME}:$SHORT_SHA

substitutions:
  _IMAGE_NAME: devops-cloud-architecture-template-1
  _REGION: asia-northeast1

options:
  logging: CLOUD_LOGGING_ONLY