version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: nest-prisma-pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: nest-prisma
    ports:
      - "5434:5432"
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - nest-prisma-net
  elasticsearch:
    container_name: nest-prisma-es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    volumes:
      - ./elasticsearch_data/config/certs:/usr/share/elasticsearch/config/certs
      - ./elasticsearch_data/data:/usr/share/elasticsearch/data
    networks:
      - nest-prisma-net
    ports:
      - 9200:9200
  kibana:
    container_name: nest-prisma-kb
    image: docker.elastic.co/kibana/kibana:8.7.0
    environment:
      - ELASTICSEARCH_HOSTS=http://nest-prisma-es:9200
    volumes:
      - ./kibana_data/config/certs:/usr/share/kibana/config/certs
      - ./kibana_data/data:/usr/share/kibana/data
    networks:
      - nest-prisma-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
networks:
  nest-prisma-net:
    driver: bridge