apiVersion: skaffold/v2beta16
kind: Config
metadata: 
  name: gke-app

build:
  artifacts:
  - image: asia-northeast1-docker.pkg.dev/dev-pct/webapp-repo/webapp
    docker:
      cacheFrom:
      - asia-northeast1-docker.pkg.dev/dev-pct/webapp-repo/webapp
  googleCloudBuild:
    projectId: dev-pct

deploy:
  kustomize:
    paths:
    - k8s/overlays/dev

profiles:
- name: dev
  deploy:
    kustomize:
      paths:
      - './k8s/overlays/dev'

- name: staging
  deploy:
    kustomize:
      paths:
      - './k8s/overlays/staging'

- name: prod
  deploy:
    kustomize:
      paths:
      - './k8s/overlays/prod'

# deploy: