apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  template:
    spec:
      containers:
      - name: webapp
        image: gcr.io/pct/nest-prisma
        imagePullPolicy: Always