kind: Service
apiVersion: v1
metadata:
  name: webapp-sample
spec:
  ports:
  - name: http
    port: 4000
    targetPort: 4000
    protocol: TCP
  type: LoadBalancer
  selector:
    app: webapp-sample