kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-deployment-sample
spec:
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: webapp-sample
      labels:
        env: dev
    spec:
      containers:
      - name: webapp-sample
        image: webapp-sample
        imagePullPolicy: IfNotPresent
        env:
        - name: VERSION
          value: dev