kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-deployment
spec:
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      name: webapp
      labels:
        env: dev
    spec:
      containers:
      - name: webapp
        image: asia-northeast1-docker.pkg.dev/dev-pct/webapp-repo/webapp
        imagePullPolicy: Always
        env:
        - name: VERSION
          value: dev