name: CI
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: root
          POSTGRES_DB: nest-prisma
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 19.x
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Build
        run: yarn run build
      - name: Run lint
        run: yarn run lint
      - name: Run unit tests
        run: yarn run test
      - name: Run e2e tests
        run: yarn run test:e2e
        env:
          DATABASE_URL: postgresql://postgres:root@localhost:5432/nest-prisma?schema=public
      