kind: Deployment
apiVersion: apps/v1
metadata:
  name: webapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      env: staging
  template:
    metadata:
      name: webapp
      labels:
        env: staging
    spec:
      containers:
      - name: webapp
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        env:
        - name: VERSION
          value: staging